version: "3"
include:
  - docker-compose.yaml  #with serviceB declared
services:
  portainer:
    image: portainer/portainer-ce:latest
    network_mode: host
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - registry #use serviceB directly as if it was declared in this Compose file
